/**
 * @deprecated — Mock data kept for PlanningChat demo fallback only.
 * All real data now flows from the backend API via lib/api.ts.
 * Do not add new imports of this file.
 */
import { Trip, City, Hotel } from './types';
import { rankHotels } from './hotelScore';

/** Helper: build a city, ranking its hotels and selecting the top one. */
function buildCity(
  city: Omit<City, 'hotels' | 'selectedHotelIndex' | 'hotel'> & { hotels: Hotel[] }
): City {
  const ranked = rankHotels(city.hotels);
  return {
    ...city,
    hotels: ranked,
    selectedHotelIndex: 0,
    hotel: ranked[0], // back-compat: top-ranked hotel
  };
}

export const mockTrip: Trip = {
  id: 'mock-1',
  title: 'Rome · Florence · Barcelona · Lisbon',
  status: 'planning',
  // Default = sum of top-ranked hotel × nights × travelers + transportOut
  // (matches what `liveTripTotal` computes against the default selections).
  totalCost: 3879,
  savings: 612,
  travelers: 3,
  savingsTips: [
    'Taking the Frecciarossa train Rome → Florence saves $43 per person vs flying — and arrives city center to city center',
    'Flying Tuesday instead of Friday saves $120 per person on the Florence → Barcelona leg',
    'Your optimized route order (Rome first, Lisbon last) saves $249 vs the most common Lisbon → Rome routing',
  ],
  cities: [
    buildCity({
      name: 'Rome',
      country: 'Italy',
      vibes: ['history', 'food'],
      dates: { arrival: '2026-06-14', departure: '2026-06-17' },
      transportIn: {
        mode: 'flight',
        operator: 'Ryanair',
        flightNumber: 'FR 1834',
        duration: '2h 20m',
        price: 89,
        from: 'London Stansted (STN)',
        to: 'Rome Ciampino (CIA)',
        departDate: '2026-06-14',
        departTime: '07:40',
        arriveTime: '11:00',
        fromStation: 'STN · Terminal 1, Gate 42',
        toStation: 'CIA · Terminal B',
        layovers: 0,
        baggage: '1 carry-on (10kg) + 1 personal item',
        bookingUrl: 'https://www.ryanair.com',
      },
      transportOut: {
        mode: 'train',
        operator: 'Trenitalia Frecciarossa',
        trainNumber: 'FR 9522',
        duration: '1h 32m',
        price: 35,
        from: 'Roma Termini',
        to: 'Firenze Santa Maria Novella',
        departDate: '2026-06-17',
        departTime: '09:15',
        arriveTime: '10:47',
        fromStation: 'Roma Termini · Platform 12',
        toStation: 'Firenze S.M.N. · Platform 5',
        layovers: 0,
        baggage: 'Unlimited luggage included',
        bookingUrl: 'https://www.trenitalia.com',
        alternatives: [
          {
            mode: 'train',
            operator: 'Italo',
            trainNumber: 'IT 9915',
            duration: '1h 35m',
            price: 32,
            from: 'Roma Termini',
            to: 'Firenze Santa Maria Novella',
            departDate: '2026-06-17',
            departTime: '11:00',
            arriveTime: '12:35',
            fromStation: 'Roma Termini · Platform 8',
            toStation: 'Firenze S.M.N. · Platform 3',
            layovers: 0,
            baggage: 'Unlimited luggage included',
            bookingUrl: 'https://www.italotreno.it',
          },
          {
            mode: 'train',
            operator: 'Trenitalia Frecciarossa',
            trainNumber: 'FR 9540',
            duration: '1h 30m',
            price: 38,
            from: 'Roma Termini',
            to: 'Firenze Santa Maria Novella',
            departDate: '2026-06-17',
            departTime: '14:15',
            arriveTime: '15:45',
            fromStation: 'Roma Termini · Platform 14',
            toStation: 'Firenze S.M.N. · Platform 5',
            layovers: 0,
            baggage: 'Unlimited luggage included',
            bookingUrl: 'https://www.trenitalia.com',
          },
          {
            mode: 'flight',
            operator: 'ITA Airways',
            flightNumber: 'AZ 1678',
            duration: '1h 10m',
            price: 118,
            from: 'Rome Fiumicino (FCO)',
            to: 'Florence Peretola (FLR)',
            departDate: '2026-06-17',
            departTime: '10:30',
            arriveTime: '11:40',
            fromStation: 'FCO · Terminal 1',
            toStation: 'FLR · Terminal A',
            layovers: 0,
            baggage: '1 carry-on included; checked bag $30',
            bookingUrl: 'https://www.ita-airways.com',
          },
        ],
      },
      hotels: [
        {
          name: 'Casa Trastevere B&B',
          rating: 4.5,
          pricePerNight: 110,
          area: 'Trastevere',
          locationScore: 0.8,
          taxesPerNight: 9,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Hotel Pantheon View',
          rating: 4.2,
          pricePerNight: 95,
          area: 'Historic Centre',
          locationScore: 0.95,
          taxesPerNight: 8,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Termini Plaza',
          rating: 3.9,
          pricePerNight: 72,
          area: 'Esquilino',
          locationScore: 0.55,
          taxesPerNight: 6,
          bookable: false,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Roma Boutique Suites',
          rating: 4.7,
          pricePerNight: 145,
          area: 'Spagna',
          locationScore: 0.7,
          taxesPerNight: 12,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Villa Borghese Inn',
          rating: 4.4,
          pricePerNight: 130,
          area: 'Pinciano',
          locationScore: 0.85,
          taxesPerNight: 10,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
      ],
      activities: [
        'Colosseum & Roman Forum',
        'Vatican Museums & Sistine Chapel',
        'Evening walk in Trastevere',
      ],
      restaurants: [
        { name: 'Da Enzo al 29', cuisine: 'Roman', priceRange: '€€' },
        { name: 'Supplì Roma', cuisine: 'Street food', priceRange: '€' },
      ],
    }),
    buildCity({
      name: 'Florence',
      country: 'Italy',
      vibes: ['art', 'romance'],
      dates: { arrival: '2026-06-17', departure: '2026-06-19' },
      transportIn: {
        mode: 'train',
        operator: 'Trenitalia Frecciarossa',
        trainNumber: 'FR 9522',
        duration: '1h 32m',
        price: 35,
        from: 'Roma Termini',
        to: 'Firenze Santa Maria Novella',
        departDate: '2026-06-17',
        departTime: '09:15',
        arriveTime: '10:47',
        baggage: 'Unlimited luggage included',
      },
      transportOut: {
        mode: 'flight',
        operator: 'Vueling',
        flightNumber: 'VY 6303',
        duration: '1h 50m',
        price: 62,
        from: 'Florence Peretola (FLR)',
        to: 'Barcelona El Prat (BCN)',
        departDate: '2026-06-19',
        departTime: '13:20',
        arriveTime: '15:10',
        fromStation: 'FLR · Terminal A',
        toStation: 'BCN · Terminal 1',
        layovers: 0,
        baggage: '1 carry-on (10kg) included; checked bag $28',
        bookingUrl: 'https://www.vueling.com',
        alternatives: [
          {
            mode: 'flight',
            operator: 'Ryanair',
            flightNumber: 'FR 4128',
            duration: '1h 45m',
            price: 48,
            from: 'Pisa (PSA)',
            to: 'Barcelona El Prat (BCN)',
            departDate: '2026-06-19',
            departTime: '06:30',
            arriveTime: '08:15',
            fromStation: 'PSA · Terminal 1',
            toStation: 'BCN · Terminal 2',
            layovers: 0,
            baggage: '1 personal item only; carry-on $25',
            bookingUrl: 'https://www.ryanair.com',
          },
          {
            mode: 'flight',
            operator: 'Vueling',
            flightNumber: 'VY 6307',
            duration: '1h 50m',
            price: 74,
            from: 'Florence Peretola (FLR)',
            to: 'Barcelona El Prat (BCN)',
            departDate: '2026-06-19',
            departTime: '18:45',
            arriveTime: '20:35',
            fromStation: 'FLR · Terminal A',
            toStation: 'BCN · Terminal 1',
            layovers: 0,
            baggage: '1 carry-on (10kg) included; checked bag $28',
            bookingUrl: 'https://www.vueling.com',
          },
          {
            mode: 'train',
            operator: 'Trenitalia + SNCF',
            trainNumber: 'FR 9601 + TGV 6207',
            duration: '11h 40m',
            price: 142,
            from: 'Firenze Santa Maria Novella',
            to: 'Barcelona Sants',
            departDate: '2026-06-19',
            departTime: '07:10',
            arriveTime: '18:50',
            fromStation: 'Firenze S.M.N. · Platform 2',
            toStation: 'Barcelona Sants',
            layovers: 1,
            baggage: 'Unlimited luggage included',
            bookingUrl: 'https://www.trenitalia.com',
          },
        ],
      },
      hotels: [
        {
          name: 'Hotel Davanzati',
          rating: 4.5,
          pricePerNight: 105,
          area: 'Centro Storico',
          locationScore: 0.95,
          taxesPerNight: 8,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Riverside Florence',
          rating: 4.3,
          pricePerNight: 90,
          area: 'Oltrarno',
          locationScore: 0.78,
          taxesPerNight: 7,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Duomo Stay Inn',
          rating: 4.0,
          pricePerNight: 78,
          area: 'Centro',
          locationScore: 0.88,
          taxesPerNight: 6,
          bookable: false,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Palazzo San Niccolò',
          rating: 4.6,
          pricePerNight: 130,
          area: 'San Niccolò',
          locationScore: 0.72,
          taxesPerNight: 11,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Antica Torre Tornabuoni',
          rating: 4.7,
          pricePerNight: 145,
          area: 'Tornabuoni',
          locationScore: 0.92,
          taxesPerNight: 12,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
      ],
      activities: [
        'Uffizi Gallery & Statue of David',
        'Climb the Duomo cupola',
        'Sunset at Piazzale Michelangelo',
      ],
      restaurants: [
        { name: 'Trattoria Mario', cuisine: 'Tuscan', priceRange: '€€' },
        { name: 'All\u2019Antico Vinaio', cuisine: 'Sandwiches', priceRange: '€' },
      ],
    }),
    buildCity({
      name: 'Barcelona',
      country: 'Spain',
      vibes: ['beach', 'nightlife', 'art'],
      dates: { arrival: '2026-06-19', departure: '2026-06-22' },
      transportIn: {
        mode: 'flight',
        operator: 'Vueling',
        flightNumber: 'VY 6303',
        duration: '1h 50m',
        price: 62,
        from: 'Florence Peretola (FLR)',
        to: 'Barcelona El Prat (BCN)',
        departDate: '2026-06-19',
        departTime: '13:20',
        arriveTime: '15:10',
        baggage: '1 carry-on (10kg) included',
      },
      transportOut: {
        mode: 'flight',
        operator: 'Vueling',
        flightNumber: 'VY 8412',
        duration: '1h 55m',
        price: 54,
        from: 'Barcelona El Prat (BCN)',
        to: 'Lisbon Humberto Delgado (LIS)',
        departDate: '2026-06-22',
        departTime: '10:45',
        arriveTime: '11:40',
        fromStation: 'BCN · Terminal 1',
        toStation: 'LIS · Terminal 1',
        layovers: 0,
        baggage: '1 carry-on (10kg) included; checked bag $32',
        bookingUrl: 'https://www.vueling.com',
        alternatives: [
          {
            mode: 'flight',
            operator: 'Ryanair',
            flightNumber: 'FR 8237',
            duration: '2h 00m',
            price: 42,
            from: 'Barcelona El Prat (BCN)',
            to: 'Lisbon Humberto Delgado (LIS)',
            departDate: '2026-06-22',
            departTime: '06:15',
            arriveTime: '07:15',
            fromStation: 'BCN · Terminal 2',
            toStation: 'LIS · Terminal 1',
            layovers: 0,
            baggage: '1 personal item only; carry-on $25',
            bookingUrl: 'https://www.ryanair.com',
          },
          {
            mode: 'flight',
            operator: 'TAP Portugal',
            flightNumber: 'TP 1045',
            duration: '1h 55m',
            price: 89,
            from: 'Barcelona El Prat (BCN)',
            to: 'Lisbon Humberto Delgado (LIS)',
            departDate: '2026-06-22',
            departTime: '15:30',
            arriveTime: '16:25',
            fromStation: 'BCN · Terminal 1',
            toStation: 'LIS · Terminal 1',
            layovers: 0,
            baggage: '1 carry-on + checked bag included',
            bookingUrl: 'https://www.flytap.com',
          },
          {
            mode: 'train',
            operator: 'Renfe + hotel transfer',
            trainNumber: 'AVE 2180',
            duration: '14h 25m',
            price: 168,
            from: 'Barcelona Sants',
            to: 'Lisboa Oriente',
            departDate: '2026-06-22',
            departTime: '08:20',
            arriveTime: '22:45',
            fromStation: 'Barcelona Sants',
            toStation: 'Lisboa Oriente',
            layovers: 2,
            baggage: 'Unlimited luggage included',
            bookingUrl: 'https://www.renfe.com',
          },
        ],
      },
      hotels: [
        {
          name: 'Hostal Grau',
          rating: 4.1,
          pricePerNight: 78,
          area: 'El Raval',
          locationScore: 0.78,
          taxesPerNight: 6,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Praktik Garden',
          rating: 4.3,
          pricePerNight: 95,
          area: 'Eixample',
          locationScore: 0.82,
          taxesPerNight: 8,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Hotel Casa Bonay',
          rating: 4.4,
          pricePerNight: 110,
          area: 'Eixample',
          locationScore: 0.85,
          taxesPerNight: 9,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Barceló Raval',
          rating: 4.2,
          pricePerNight: 135,
          area: 'El Raval',
          locationScore: 0.8,
          taxesPerNight: 11,
          bookable: false,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'The Serras',
          rating: 4.6,
          pricePerNight: 185,
          area: 'Barri Gòtic',
          locationScore: 0.95,
          taxesPerNight: 15,
          bookable: true,
          bookingUrl: 'https://www.booking.com',
        },
      ],
      activities: [
        'Sagrada Familia',
        'Park Güell',
        'La Boqueria & Gothic Quarter',
      ],
      restaurants: [
        { name: 'Bar Cañete', cuisine: 'Catalan tapas', priceRange: '€€€' },
        { name: 'El Xampanyet', cuisine: 'Tapas & cava', priceRange: '€€' },
      ],
    }),
    buildCity({
      name: 'Lisbon',
      country: 'Portugal',
      vibes: ['food', 'history', 'nightlife'],
      dates: { arrival: '2026-06-22', departure: '2026-06-25' },
      transportIn: {
        mode: 'flight',
        operator: 'Vueling',
        flightNumber: 'VY 8412',
        duration: '1h 55m',
        price: 54,
        from: 'Barcelona El Prat (BCN)',
        to: 'Lisbon Humberto Delgado (LIS)',
        departDate: '2026-06-22',
        departTime: '10:45',
        arriveTime: '11:40',
        baggage: '1 carry-on (10kg) included',
      },
      transportOut: {
        mode: 'flight',
        operator: 'TAP Air Portugal',
        flightNumber: 'TP 1364',
        duration: '2h 30m',
        price: 112,
        from: 'Lisbon Humberto Delgado (LIS)',
        to: 'London Heathrow (LHR)',
        departDate: '2026-06-25',
        departTime: '17:25',
        arriveTime: '19:55',
        fromStation: 'LIS · Terminal 1',
        toStation: 'LHR · Terminal 2',
        layovers: 0,
        baggage: '1 carry-on + 1 checked bag (23kg) included',
        bookingUrl: 'https://www.flytap.com',
      },
      hotels: [
        {
          name: 'Lisbon Story Guesthouse',
          rating: 4.1,
          pricePerNight: 65,
          area: 'Bairro Alto',
          locationScore: 0.85,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'LX Boutique Hotel',
          rating: 4.3,
          pricePerNight: 88,
          area: 'Cais do Sodré',
          locationScore: 0.88,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Browns Central Hotel',
          rating: 4.4,
          pricePerNight: 98,
          area: 'Baixa',
          locationScore: 0.9,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Pousada de Lisboa',
          rating: 4.5,
          pricePerNight: 135,
          area: 'Praça do Comércio',
          locationScore: 0.92,
          bookingUrl: 'https://www.booking.com',
        },
        {
          name: 'Memmo Alfama',
          rating: 4.6,
          pricePerNight: 155,
          area: 'Alfama',
          locationScore: 0.82,
          bookingUrl: 'https://www.booking.com',
        },
      ],
      activities: [
        'Belém Tower & Jerónimos Monastery',
        'Tram 28 through Alfama',
        'Sintra day trip',
      ],
      restaurants: [
        { name: 'Taberna da Rua das Flores', cuisine: 'Portuguese', priceRange: '€€' },
        { name: 'Time Out Market', cuisine: 'Market hall', priceRange: '€€' },
      ],
    }),
  ],
};
